---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelttered-homeless-prod-wrk-deployment
  labels:
    app: shelttered-homeless-prod-wrk
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shelttered-homeless-prod-wrk
  template:
    metadata:
      labels:
        app: shelttered-homeless-prod-wrk
        env: prod
    spec:
      containers:
        - name: shelttered-homeless-prod-wrk
          image: ig7235/shelttered-homeless-app-wrk:1.0
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: 10.97.32.146
