---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelttered-homeless-prod-api-deployment
  labels:
    app: shelttered-homeless-prod-api
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelttered-homeless-prod-api
  template:
    metadata:
      labels:
        app: shelttered-homeless-prod-api
        env: prod
    spec:
      containers:
        - name: shelttered-homeless-prod-api
          image: ig7235/shelttered-homeless-app-api:1.0
          imagePullPolicy: Always
          env:
          - name: REDIS_IP
            value: 10.97.32.146
          ports:
          - name: http
            containerPort: 5000
