---
apiVersion: v1
kind: Service
metadata:
  name: ig7235-test-flask-service
  labels:
    username: "ig7235"
    env: "test"
spec:
  type: ClusterIP
  selector:
    app: "ig7235-test-flask"
  ports:
  - name: ig7235-test-flask
    port: 5000
    targetPort: 5000
~                             
