---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ig7235-test-data
  labels:
    username: "ig7235"
    env: "test"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
