---
apiVersion: v1
kind: Service
metadata:
  name: ig7235-test-redis-service
  labels:
    username: "ig7235"
    env: "test" 
spec:
  type: ClusterIP
  selector:
    app: "ig7235-test-redis"
  ports:
  - name: ig7235-test-redis
    port: 6379
    targetPort: 6379
