---
version: '3'
services:
    redis:
        image: redis:latest
        container_name: ig7235-redis
        ports:
            - 6391:6379
        user: "869573:816966"
        volumes:
            - ./redis-docker/config/:/data
        command: ["redis-server", "/data/redis.conf"]
    web: 
        build: .
        container_name: ig7235-web
        ports:
            - 5011:5000
        volumes: 
            - ./redis-docker/data/data_file.json:/datafile.json
          
